### ISSUE TITLE
Which (programming) language should you learn first?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/start-here#102]
What programming language should you learn first?
This is a _really good question_ beginners often ask. there _appears_ to be an _answer_:
https://medium.freecodecamp.com/what-programming-language-should-i-learn-first-ʇdıɹɔsɐʌɐɾ-ɹǝʍsuɐ-19a33b0a467d

**Comment by iteles** [comment]
@nelsonic As our community has grown over the last 9 months, the newer issues are getting more traction and this question was asked again: https://github.com/dwyl/start-here/issues/141

Can I propose we add this link to that issue and close this one?

**Comment by nelsonic** [comment]
See: https://github.com/dwyl/start-here/issues/141#issuecomment-419643356 and https://github.com/dwyl/learn-elixir/issues/102
