### ISSUE TITLE
co-founder(s) wanted!

### ISSUE THREAD

**Issue by nelsonic** [dwyl/start-here#108]
![image](https://cloud.githubusercontent.com/assets/194400/20654187/c15bf154-b50e-11e6-9c6f-da5763c2db10.png)

But _seriously_... 

# we need ***`people`*** who are ***`passionate`*** about using ***`technology`*** to ***`solve real problems`*** and _systematically_ make the world ~~better~~ ***`best`*** for everyone/thing on the `planet`! 

If this sounds like you, please read our: [**manifesto.md**](https://github.com/dwyl/start-here/blob/master/manifesto.md) (_if you haven't already!_)
***`And`*** _show_ us your interest by Pull-Request-ing to **update**/***improve*** _something_ in the Manifesto (_e.g: add/propose an item on the list_) or pick one of these issues: https://github.com/dwyl/start-here/issues?q=is%3Aissue+is%3Aopen+label%3Amanifesto 

We have **_Big_ Plans** and we've _invested_ the last [`Nine Thousand Hours`](https://www.youtube.com/watch?v=DNX-g8TMyyY) accumulating the [knowledge](https://github.com/nelsonic/g8/issues/53#issuecomment-180877634) and _cash_ to `#DWYL` without needing _any_ "external" funding so that we can stay `true` to our Manifesto of growing Organically (_by revenue_) and being accountable _exclusively_ to our community/team. (_AKA the [Macklemore](https://www.youtube.com/watch?v=2zNSgSzhBfM) [Model](https://www.techdirt.com/blog/casestudies/articles/20130401/03115322523/macklemore-explains-why-not-being-label-helped-him-succeed.shtml) `->` focus on long-term and don't "sell out" if you don't have to!!_)

> _We `need` **your** help fleshing out the `details` and implementing the **`Plan`**_

Highlights:
+ [x] You're joining a [`team`](http://www.dwyl.io/team) of people who have worked in _many_ organisations, studied hundreds more and _systematically_ gathered the best ideas from all for how to create the _best_ `culture` (_we need help putting it all into words and making it all happen!_)
+ [x] DWYL is an existing `Profitable` Business with Real Interesting Customers/Partners, a `Pipeline` of more Socially-beneficial Projects and a _Plan_ to get _Many_ More. We are `people-focussed` (_Not Profits!_) but being financially-sustainable organisation is the _beating heart_ of our `mission` and means we can always _pay_ people (_because city rent, bills & food isn't free!!_) and everyone can `#DWYL`! 
+ [x] _Focus_ on building **Scalable Sustainable Software `Product(s)`**. You will experience and be work on the _complete_ `Lean` Software Development Lifecycle.
+ [x] "_Market_-level" Compensation (_so you don't have to `think` about money and can focus on the `Mission`_)
+ [x] _Founder_ `Equity`. Your shares will be _worth_ something from day one (_e.g. if you need to sell a few to buy a house_) and you will be _directly_ in _control_ of what they will be worth in 2-10 years! 
+ [x] You will be given `autonomy` and `responsibility` and expected to be `accountable`.

![passionate-interest](https://cloud.githubusercontent.com/assets/194400/20655496/f02da66a-b51a-11e6-8e35-78c2baaab897.png)

P.S. If you ❤️  [`Spreadsheets`](https://www.google.co.uk/search?q=love+spreadsheets&tbm=isch) we have a _few_ you can get _stuck_ into which we want/need to convert into [real-time-insights](https://www.google.co.uk/search?q=beautiful+dashboard&tbm=isch) 😉

**Comment by nelsonic** [comment]
@iteles just pointed out that this sounds like an "Open Invitation" to _anyone_ to become a co-founder of DWYL ... and in a way, it is. But to be clear: I only opened this issue to _signal_ that we are at the stage in the DWYL journey where we are _looking_ for a co-founder and not that _everyone_ will _automatically_ become one just by sending us a PR to update the manifesto!

While I don't like the idea of a "Job Application" because I have a _negative association_ with the word Job ... https://www.youtube.com/watch?v=psM9DoCzuoQ 
However for the purposes of finding people who want to `commit` to our mission, requiring people to submit a Pull Request to _improve_ the manifesto is a good ***first step*** in the process ...

This issue is to make sure that _everyone_ is _aware_ that we are _actively_ looking for a _great_ person (_or multiple people_) to _engage_ with us in taking the DWYL Mission forward. In the spirit of _complete transparency_ we want _everyone_ to know what our plan is!

**Comment by iteles** [comment]
@markwilliamfirth I think @newswim is right, there is a wealth of information in this issue that should be in our `start-here` readme asap until I'm able to iterate on it and write something up more fully. 
Are you happy to put in a PR to add this info to the readme? :blush:

**Comment by nelsonic** [comment]
no longer relevant.
