### ISSUE TITLE
Mission

### ISSUE THREAD

**Issue by nelsonic** [dwyl/start-here#116]
@iteles wrote the _current_ mission in _early_ 2015: https://github.com/dwyl/start-here/commit/11f0cad298d64543b1bed53820f8cdaab7429528#commitcomment-20720785
is there a case for _simplifying_ it...?

**Comment by markwilliamfirth** [comment]
We need to agree on a clear mission statement for the company. Some I have already seen heard are:

+ We simplify. We enable people to get through their need-tos efficiently so they can get to their want-tos.
+ To solve life's challenges.
+ To enable others to find their purpose and meaning in life

@iteles @nelsonic what are thoughts on the above and other variations of the themes?

**Comment by nelsonic** [comment]
@markwilliamfirth agreed. this needs to be sorted _asap_!
did you see: https://github.com/dwyl/start-here/commit/11f0cad298d64543b1bed53820f8cdaab7429528#commitcomment-20720785 ? 😉

**Comment by nelsonic** [comment]
@iteles I'm happy for you to define the mission (_in the simplest possible terms_) and I will focus on tech and product dev. 👍

**Comment by markwilliamfirth** [comment]
@iteles we should define this

**Getting things done**

e.g.
Helping people do more
Helping people get things done

**Individual Potential**

e.g.
To help people reach their potential
To help people to achieve their potential

**Human Potential**
This has a slightly more transhumanist edge to it and suggests using technology to augment humans
e.g.
To extend human potential
To augment human potential

**Comment by YvesMuyaBenda** [comment]
Hello guys! Though this is properly an in-house thing, perhaps the external perspective of someone figuring out what the heck is going on might be useful? In brief conversations with @nelsonic, part of  the vibe I was getting is helping folk reach their potential by given them access to an education that gives them practical skills that leverage whatever are their existing talents--applicable intelligence in constructing, creating stuff which one can easily see has a positive impact on the enviroment. The timer app, gave me a sense of  creating specific tools that "augment" what a person already does, so, in this pariticular case making more of one's potential by making more of time (analogous to how a use of the Podmoro timer technique creates a heightened sense of time passing,  of urgency). Now the helping of individuals reach their potential is for me best seen in  the  associated Founders and Coders initiative/community, where, similar to dwyl, the ethods is one of helping each other, colloboration, sharing knowledge, the individual being improved by the group collectively being improved, and the collective being improved, by the individual being improved.

Hope these observations are of some use!

**Comment by markwilliamfirth** [comment]
@YvesMuyaBenda and @newswim thank you for your input - anyone else reading who has some insight to share please do jump in

DWYL has a broad mission and then the products created within the organisation will have their own missions and focuses. Agreed that the Time app will most likely have a mission relating more closely to what you've described above - DWYL has a broader remit than Time though, although that doesn't mean the missions won't be similarly worded.

Although it won't necessarily be focused and specific, defining the broad mission for the organisation will allow us to utilise a consistent message with the right wording across our website, social media etc and that's what we're trying to do here.

There is overlap and a fine line between the org mission and ethos, vision, and product missions and we need to make sure we define these somewhere too.

If you were interested the mission of F&C is currently the following:
>The mission of Founders & Coders is to open access to education by building democratically organised learning communities where people study creative technology.

**Comment by YvesMuyaBenda** [comment]
@markwilliamfirth well, yeah, the Founders and Coders was used as a contrast to try to better word what I was perceiving. For sure, I did not think that the timeapp was all that was going one, but that it fit within a certain genre, of helping folk to enhance their potential by creating tools that augment what they already do, versus giving them abilities they do not already possess. Thanks very much for your feedback, this whole, out in the open thing is cool.

Yeah for the overalap and need for fine distinction between mission, ethods, vision, and product mission; I did not make that distinctions as finely as I would like, but for sure, that would all add up to a rich picture of what dwyl is all about!

**Comment by markwilliamfirth** [comment]
Thanks @YvesMuyaBenda for adding to the discussion - we're really grateful when people take the time to open our eyes to other perspectives and interpretations and that'll be really important with regards to how a mission is interpreted.

If you have any other thoughts please share them with us (and that goes for anyone else reading too!)

@iteles will leading on defining this and it's something that will probably be decided upon by the end of the week.

**Comment by YvesMuyaBenda** [comment]
@markwilliamfirth for sure, again, thanks for being open and receptive. I guess when one gets deeply involved with something it becomes more and more tricky to percieve how other folk are perceiving it, so that is what I was trying to do with my comments. I look forward to seeeing what @iteles decides upon! Onward and upward!

**Comment by iteles** [comment]
What we land on for now will be something to try on as a starter and iterate over. 

I can already see that the one line mission will probably need to be augmented with a few lines on where it comes from and the missions of the many pieces that make up the puzzle (time efficiency, learning community, health, etc). 

Super grateful for the input as always folks ❤️

**Comment by markwilliamfirth** [comment]
^agreed that the mission may change over time and iterate

What we need is an agreed wording that we can utilise across our business and brand

We will write a blog post about the mission to explain it 👍

**Comment by newswim** [comment]
I was still a little foggy on the `'wut dis?'` factor until I read https://github.com/dwyl/start-here/issues/108.

**Comment by markwilliamfirth** [comment]
<img width="1081" alt="screen shot 2017-03-17 at 16 37 28" src="https://cloud.githubusercontent.com/assets/5732209/24053279/6ef141ee-0b30-11e7-9570-eafd301ec17f.png">

We need a defined mission statement for the b-corp assessment

**Comment by markwilliamfirth** [comment]
Closed in favour of https://github.com/dwyl/hq/issues/328
