### ISSUE TITLE
Update the manifesto with an *ordered* list

### ISSUE THREAD

**Issue by iteles** [dwyl/start-here#12]
Would be nice to have an ordered list of our priorities so the things we consider most important are seen first.

**Comment by iteles** [comment]
What do we think of this preliminary order (bearing in mind people using the app) - I wish there could be 4 joint first places :disappointed: :
1. Keep it simple
2. Community driven
3. Your data is yours
4. Environmental love
5. Accessibility
6. Open source, always
7. The latest science
8. Revenue funded
9. Simple API
10. We do not have users, [we have _people_](https://github.com/ideaq/time/issues/33)
11. Reward loyalty, not sign ups
12. No forced updates

**Comment by nelsonic** [comment]
Sketch the basic mechanism by which we allow people to vote on what ***matters*** to them.

**Comment by iteles** [comment]
Absolutely! And the people who are **using** the app will have _completely different_ priorities to the people **developing* with the API for example.

We just need a starting point.

**Comment by iteles** [comment]
List of priorities external to us being dealt with in #13.
Closing this issue.

**Comment by nelsonic** [comment]
@iteles is there a reason why the list in the Manifesto went back to an *un-ordered* (*un-numberd*) list...?

**Comment by iteles** [comment]
It's not _numbered_ (it never was) but it _is_ **"in order"**.

I put the numbers in originally and then felt they were too **restrictive**. Being fully transparent, accessible and environmentally friendly are all equally important to me and strictly numbering them didn't feel right.

I don't want people to waste time quibbling with us over how _"accessibility should be number 4 and not number 5"_ on our list when really, they are all our values. I felt at the time that the order was more important that the numbering.

**Comment by nelsonic** [comment]
https://indieweb.org/principles + https://indieweb.org/Getting_Started

**Comment by Cleop** [comment]
At the moment the manifesto only has one numbered point : 1. Keep it simple. The other bullets are not numbered. 

Here are my 2 favoured options:

- Numbered points including the line found in the indieweb resource that @nelsonic shared:
**Key principles of dwyl, numbered for reference, not necessarily for any kind of priority.**

- No numbers, just bullets. But personally I would remove the current ``` 1. Keep it simple ``` as I think the formatting looks a bit confused. If keeping things simple should be held the most highly perhaps it would look better to say something like "Our number one principle is to keep things simple." And then the other bullets would follow.

What are your thoughts @iteles @nelsonic ? or anyone else?

Is there a danger that people may not read the 'no priority' disclaimer about the numbering? In which case, is no numbers the best option but with some emphasis on keeping things simple.

**Comment by Cleop** [comment]
Looks like @nelsonic has also brought up the point about the lonely point 1 in issue #96

**Comment by Cleop** [comment]
This is what @nelsonic said in issue #96 aside from recognising the issue.

"My preference is to explicitly number the sections and have section sub-headings so that we can link to a specific section. e.g: https://github.com/dwyl/start-here/blob/master/manifesto.md#your-time-should-never-be-wasted"

So it sounds like @nelsonic is in favour of numbering. I don't know whether the word 'explicitly' is meant to signify ordering by priority?

**Comment by nelsonic** [comment]
@Cleop _ideally_ we would allow _everyone_ to `vote` on their own priority for the items in the manifesto so they can make their own version. The _reason_ this would be cool would be that people could _share_ their priority with their friends/family/colleagues and everyone would know what someone's priorities (_in life_) are.

For now, we just need:
+ convert each bullet point in the manifesto into section heading so it can be linked to. 
(_an unordered list does not allow us to link to an individual item in the list..._)
+ Bonus Level: Add a new item to the list; your own (_personal_) priority for what you want to improve in the world or a "_guiding principal_" you live by.

**Comment by Cleop** [comment]
Following #122, is this issue in a position to be closed? @iteles @nelsonic

**Comment by nelsonic** [comment]
@Cleop yes, thanks again! 🎉
