### ISSUE TITLE
awaiting-review label does not exist but is part of the process in the contributing guide

### ISSUE THREAD

**Issue by Cleop** [dwyl/start-here#123]
The dwyl contributing repo says to:

> Apply the awaiting-review label to the PR.

...when following the correct procedure to make a PR.

From https://github.com/dwyl/contributing

However, this label does not exist on this repo. Is this intentional? Does it need recreating?

**Comment by nelsonic** [comment]
@Cleop if you ever need a label in a repo, use: http://label-sync.herokuapp.com 👍

**Comment by Cleop** [comment]
Thanks @nelsonic , I just wanted to double check that the documentation wasn't out of date as all of the other labels seemed to already be in place.
