### ISSUE TITLE
Markdown errors on manifesto

### ISSUE THREAD

**Issue by Cleop** [dwyl/start-here#128]
**The manifesto has ugly markdown errors and missing formatting in a couple of places:**

![image](https://cloud.githubusercontent.com/assets/16775804/24151696/668addc6-0e41-11e7-8759-ecb6eb107960.png)

**This is what the code looks like:**

![image](https://cloud.githubusercontent.com/assets/16775804/24151719/7aca6fe0-0e41-11e7-909e-1b8e581a6c25.png)

**This is what atom's markdown previewer shows:**

![image](https://cloud.githubusercontent.com/assets/16775804/24151724/7f43b6b2-0e41-11e7-9d82-31b4bb3f47ef.png)

**This is what this particular excerpt looked liked in the PR I made that edited manifesto.md:**

![image](https://cloud.githubusercontent.com/assets/16775804/24151799/a97289cc-0e41-11e7-8fc3-58cc29bd12ad.png)

I can't see what's wrong with the code. Anyone else got any ideas?

**Comment by iteles** [comment]
@cleop It needs the extra line break that was removed in your PR!
If we put that back after 'wasted.', it should be fine :+1:
