### ISSUE TITLE
Update "Faces" Image in start-here README ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/start-here#139]
Currently our "Who" picture is _ancient_: https://github.com/dwyl/start-here/tree/f072680ba4bb099fbd0aa821d4f50b14df30c98a#who
![image](https://user-images.githubusercontent.com/194400/28011239-8f1b41da-6559-11e7-8fe3-e41eded74414.png)

I created a new version of the image in:
https://github.com/dwyl/stars#want-to-sort-the-profile-images-by-color
and have cropped and _optimised_ the image down to **300kb**:
![dwyl-thousand-faces](https://user-images.githubusercontent.com/194400/28011265-a95f52d4-6559-11e7-823e-6133d947921a.jpg)
(_so hopefully it's not too big for people reading `start-here` on a mobile device ..._)

Markdown:
```
[![dwyl-community](https://user-images.githubusercontent.com/194400/28011265-a95f52d4-6559-11e7-823e-6133d947921a.jpg)](https://github.com/dwyl/who)
```

If people _agree_ that we should update the image,
and someone has time to make a PR, please go for it! 👍

**Comment by karinakozarova** [comment]
I could make a PR if the attached picture is the one that should be added?

**Comment by iteles** [comment]
Yea, I think this would be good 🎉

**Comment by nelsonic** [comment]
@karinakozarova thanks! 👍
