### ISSUE TITLE
Want to join the dwyl community?

### ISSUE THREAD

**Issue by iteles** [dwyl/start-here#143]
We've had a few lovely folk mention in our gitter room that they're keen to join the community and don't know how!

<img width="522" alt="screen shot 2017-12-11 at 21 00 44" src="https://user-images.githubusercontent.com/4185328/33853623-757b1256-deb6-11e7-8e85-0b33678cb294.png">

For now,  if you'd like to join us, just star this repo and add a comment here as to why and we'll invite you to join! ✨

**Comment by leordev** [comment]
Thanks @iteles!

**Comment by linuxenko** [comment]
I would like to be invited too :cat2:

**Comment by hectonpdomingos** [comment]
Hey! I love it all! Can I join in? I would love to help somehow.

**Comment by SecondHJ** [comment]
Looks great! I will love to be a part of this community ~

**Comment by anweshknayak** [comment]
@iteles if you could invite me too :)

**Comment by iteles** [comment]
This issue makes me so happy. Wonderful to have you all join us! 🎉

**Comment by prashant0598** [comment]
@iteles will love to be part of this organization 😄

**Comment by debck** [comment]
hey ! I would like to join the community ?
i find  really quality stuff and would like to learn and contribute

**Comment by da-edra** [comment]
I'd love to contribute! 😄

**Comment by adrian-tiberius** [comment]
Hi! I would like to join and contribute!

**Comment by olstenlarck** [comment]
So welcome! :)

_(long, but not pretty active member here ;/)_

**Comment by divayprakash** [comment]
Hey! I would love to carry forward the awesome work you're doing and spread the word about it! Do add me to the community!

**Comment by itsN1X** [comment]
hola!

I'd love to be a part of the community too. <3

**Comment by itsN1X** [comment]
hola!
I'd love to be a part of the community too :heart_eyes:

**Comment by ultrasounder** [comment]
Hi would like to learn at the feet of the Gurus in this community and contribute back in whatever way possible. May I please request an invite?

**Comment by JLezac** [comment]
I really like the positive and gentle vibe of this community, I would love to be part of the community. :pray:

**Comment by pragmaticpi** [comment]
Hi,
I had already contacted you regarding to be part of the community. I am new to open source world and I would like very much to contribute and learn through your open source projects.
Do add me to your community.
Thanks

**Comment by achiv** [comment]
Hello,
I would love to be part of this and contribute :)

**Comment by danilocecilia** [comment]
Hi, I got really excited about what you guys are doing, I definitely want to be part of this organization. I would love to help and also would love to learn from you guys too.

Thanks for the opportunity!

**Comment by mleyb** [comment]
hello there - could request to be added to the community too? I’d like to contribute

**Comment by mleyb** [comment]
thank you all :)

**Comment by olstenlarck** [comment]
Welcome! :tada:

**Comment by thegauravtiwari** [comment]
Hello. I saw the dayum interesting docs of this repo. Would love to contribute to the projects and flowering new ideas. Please send me invite to join this organisation

**Comment by Mayankjh** [comment]
Hi, I would love to get my hands on code with the community can i please have an invite...

**Comment by pg07codes** [comment]
Hii . i do what i love. And that's why i find this organisation really great. Lots of great resources at a single place. i would love to join the community.

**Comment by luckylittle** [comment]
+1

**Comment by swetajena98** [comment]
hey!I am overwhelmed by the quality of repos this community contains. would love to join and contribute.

**Comment by codeshifu** [comment]
I am most proud of the future you guys are building here and would love be a part of this amazing journey and contribute (in my own little way) to it. 👍

**Comment by iteles** [comment]
Thank you @swetajena98 and @codeshifu ❤️ We're looking forward to seeing your contributions and thoughts in the issues, welcome to dwyl!

**Comment by codeshifu** [comment]
Thanks, @iteles for the invitation. I'm honoured.

**Comment by VimanyuAgg** [comment]
I love the idea of `doing what you love` and really appreciate what you guys are building here. I would absolutely :heart: to be a part of this amazing community and make contributions in the best way I can.  :+1:

**Comment by VimanyuAgg** [comment]
@nelsonic Thanks for the invite! I'm thrilled to join this community :blush:

**Comment by nelsonic** [comment]
@VimanyuAgg thank _you_ for _joining_! We are just getting _started_ with building! 😉

**Comment by shan5742** [comment]
Would love to be part of the community here!

**Comment by tienpham94** [comment]
As an open source enthusiast, I appreciate what you guys are doing here, and I would love to be part of the community!

**Comment by misacorn** [comment]
I would love to also be a part of the community and start to contribute!

**Comment by prankshaw** [comment]
I will love to join this organisation

**Comment by silvaesouza** [comment]
Hello, I'm here to contribute and learn. I like dwyl's goals

**Comment by RajuKalidindi** [comment]
Hey! There are a lot of good resources you guys put together. I'd love to be a part of this organization.

**Comment by Web-Dev-Rich** [comment]
Hi there, I'm a pretty new developer (on the Skillcrush Break into Tech Blueprint) and I'm interested in open source. You have so many resources here and I would like to contribute somehow (not quite sure how yet!)

**Comment by nelsonic** [comment]
Hi @Web-Dev-Rich, glad you found @dwyl 🔍 

https://skillcrush.com looks interesting. 
![image](https://user-images.githubusercontent.com/194400/47609782-66f51c80-da3d-11e8-939d-c0cff01e0604.png)
## "Learn to code and and finally do work you actually love"

... sounds familiar ... 😉 

https://skillcrush.com/skillcrush-blueprints/#cost-enroll-link
![image](https://user-images.githubusercontent.com/194400/47609811-1f22c500-da3e-11e8-9620-c591957d254c.png)

**$1499** seems _reasonable_ by US "bootcamp" standards. 
The Syllabus [Syllabus-MVP-__-The-Break-Into-Tech-Blueprint.pdf](https://github.com/dwyl/start-here/files/2522267/Syllabus-MVP-__-The-Break-Into-Tech-Blueprint.pdf) seems "OK" ...

There's only ***one*** mention of Testing/TDD in the syllabus is **RSpec** tests in Ruby on Rails track:
![image](https://user-images.githubusercontent.com/194400/47609978-fdc3d800-da41-11e8-893c-56e30f969368.png)
I would _highly_ recommend that you focus on writing tests for your code as _soon_ as you can in your development journey; writing tests will ensure you write _less_ code and boost the reliability of the code you write. If you haven't already, see: https://github.com/dwyl/learn-tdd

If you get to the end of SkillCrush and decide you want to "_stand out_" from the crowd of people 
who go through "bootcamps" and (kinda) know Ruby-on-Rails, consider learning **`Phoenix`**! 
see: https://github.com/dwyl/learn-phoenix-framework

**`Ruby`** is a _lovely_ programming language, you won't have trouble finding work if you have the skills.
If you want the hiring manager to _prioritise_ your CV, make sure you learn **`Elixir`**. 
We have _condensed_ our Elixir learning into: https://github.com/dwyl/learn-elixir
(_if you spot an area for improvement, please open an issue and/or Pull Request!_) 
There are quite a few good `Ruby |> Elixir` resources in: https://github.com/ruby2elixir

We've been writing notes/examples/tutorials for the open source tech we _use_ for the past 5 years.
Quite a few people have found it _useful_. The _best_ way to contribute is to follow one of the **`learn-...`** guides and if anything is _unclear_, open an issue with a question! 
(_people massively underestimate the value of questions, they are the lifeblood of learning!_)

_Most_ companies/organisations "lock up" their learning on an _internal_ "Wiki" afraid that their "competitors" will "steal" their knowledge ...  
We _very much_ believe in "_**out-teach** the competition_" ... our clients & community members agree. 
Watch: http://ecorner.stanford.edu/videos/2361/Out-Teach-Your-Competition


Anyway, welcome to @dwyl we look forward to your _feedback_! 🎉

**Comment by Web-Dev-Rich** [comment]
@nelsonic Many thanks for the welcome and guidance. I have read about TDD and would definitely be "into" it.

**Comment by samagragupta** [comment]
I would like to be invited too 🐈

**Comment by iteles** [comment]
Welcome @samagragupta! Would love to know how you found us 😊

**Comment by samagragupta** [comment]
@iteles Thank you for inviting.
Found few interesting repositories: https://github.com/dwyl/todomvc-vanilla-javascript-example  https://github.com/dwyl/learn-aws-lambda https://github.com/dwyl/abase and many more.

**Comment by jamesgeorge007** [comment]
Hi there, I would like to join this vibrant community 👍

**Comment by emilshouse** [comment]
Hello, I stumbled across dwyl after googling for a reason why iTerm needed Full Disk Access. https://github.com/dwyl/dev-setup/issues/20 
There are so many great resources here and I'd be happy to contribute to this community where I can.

**Comment by nelsonic** [comment]
@emilshouse thank you for sharing that a _random_ issue about iTerm Full Disk Access was _useful_ to you. I'm always stoked when random issues show up in SERPs and people find them helpful. 🎉 
I keep trying to _encourage_ people to open issues when they see things and keep a "log" of their journey, which will then help _others_ save time ... 💭 Thanks for sharing your thoughts! (_we really appreciate it_). You have _already_ made a _great_ contribution to this community. ❤️ ✅ 

You've been invited to join dwyl on GitHub, visit https://github.com/dwyl to accept. 📥

**Comment by 2knal** [comment]
Hello everyone, I was amazed by the wonderful resources this community has put together. I would be happy to contribute to this community and learn many things!

**Comment by Koshukey** [comment]
Hello !  I  sympathise with this community philosophy "scratch your own itch" 😀
So, I want to join this community and contribute ! 😎

**Comment by withshubh** [comment]
Hey! I would like to join the org.
I got to know about dwyl when I visited the GitHub profile of one of my friend.

**Comment by nelsonic** [comment]
[![image](https://user-images.githubusercontent.com/194400/49609727-49986400-f994-11e8-93b3-3124eb31df31.png)](https://youtu.be/NsUFBm1uENs)

@withshubh we are _stoked_ you found @dwyl through one of your friends. 🎉

**Comment by foo-dogsquared** [comment]
Hey all! I found this through searching for doing unit tests (which I wish I've learned about it eariler in my learning journey) and I would like to say thanks for your resources that you put together. Really cool!

I also like to join the community since my perspective on learning is *quite* similar to your "Scratch your *own* itch" approach. I would really like to interact with people with that kind of learning approach. 😁

**Comment by hernanfiqus** [comment]
Hi dwyl! I'm Hernán from Fiqus, a software cooperative from Argentina. First of all, nice to know about you! It's pretty impressive and motivating to discover software companies in other countries that work in similar ways to us.
A few days ago we had our annual assembly and we decided to contact software companies from other countries with similar principles and ideology to work together. Argentina is not having a good economic moment, and it will be very helpfull to us to work on some projects on other countries.
Here is our website (https://fiqus.com/en) where you can find some projects we worked on. We are specialist on python, django, nodejs, react, vuejs and elixir.
So, if you think that we can help you on your projects, maybe we can have a hangout to chat and share experiences about our companies and projects.

Regards!!

**Comment by alassanecoly** [comment]
Hello ! This community is wonderful. I love the concept and the philosophy. Imho, knowledge is free and should not be something acquired by paying for bootcamps sessions for example... I'd like to join y'all to contribute and learn new things 💗

**Comment by prateeksawhney97** [comment]
Hello everyone, I would love to be a part of the organisation. The organisation has compiled a lot of quality stuff and learning resources. I would like to be a part of this.

**Comment by may12day** [comment]
@iteles I would love to be a part of this awesome organization

**Comment by anilmuppalla** [comment]
I would like to join too!

**Comment by rounakdatta** [comment]
Hey dwyl, its just the finest collection of open-source software I found on the internet. Never did I saw such care in putting down information-intensive documentations and covering such voluminous amount of knowledge. Thanks for making this world a amazingly better place! Would definitely love to be part of this community and grow together!

**Comment by Vishal-V** [comment]
I really appreciate the efforts in maintaining this organization. The repo on jwt tokens was what brought me here. I would love to contribute to React, Node and React Native repositories. Do add me to the organization. Thanks!

**Comment by zhongdeming428** [comment]
I fell in love with dwyl!Please let me join this awesome organization!  @iteles

**Comment by HeroicHitesh** [comment]
Willing to contribute and learn from the community simultaneously.:)

**Comment by AlaeddineMessadi** [comment]
I am glad that I stumbled upon your wonderful community and I would love to join you. @iteles can you please add me :)

**Comment by sourabh1031** [comment]
Hello i want to contribute to this organization because it will not only enhance and improve myself but it will also provide me one more chance to give back to the community

**Comment by abhishalya** [comment]
I would love to join the organization and contribute :)

**Comment by sbardons** [comment]
I am still in awe after reading your start-here guide. Can I please contribute to this community?

**Comment by abhishekguleri** [comment]
I would like to join too senpai :100:

**Comment by royshouvik** [comment]
Hey! Can I come aboard? Please?
*But why*
Technology - I strongly believe Elixir and Elm are the future. It's only a matter of time before the ecosystem reaches critical mass and these become widely adopted. 
Community - Who doesn't ❤️  an open and welcoming community. Gone are the days of "keep your stuff to yourself". It's all about sharing and caring now.
Scratch your own itch - I have a bit of history of doing just that...I compiled an open source data science curriculum because I couldn't find one when I wanted to study it. It became very popular with 6k stars (https://github.com/ossu/data-science).

**Comment by iteles** [comment]
@royshouvik Thank you for telling us you 'why'! 
Welcome to dwyl 💙 😊

**Comment by mbhup** [comment]
Hey, would love to join as well :)

**Comment by BaseMax** [comment]
Great.

**Comment by artysidorenko** [comment]
Hi there,

Would also love to join the community as I'm currently trying to get some open-source dev experience and see a lot of quality (and variety!!) in the repos here.

I'm 90% node.js (+ react) but also know a bit of Java and currently learning PHP if that should ever come up in future.

Cheers,
Arty

**Comment by yonahw** [comment]
Hi,

I recently began learning elixir and found your material very helpful.

I am interested in both learning more and contributing to the community. I find your approach and dedication to transparency and sharing of knowledge inspiring and would love to be a part of it.

Cheers,

Yonah

**Comment by OcelotDive** [comment]
Would love to help and contribute.

**Comment by BaseMax** [comment]
> Would love to help and contribute.

We will be happy with your cooperation. :+1: :heart:
@OcelotDive @iteles

**Comment by CoDeRgAnEsh** [comment]
Hey there,

This dwyl has been so interesting to go through. Can I join this organization? I can even blog out regarding technical stuffs.

Loved to be invited into. Cheers🎉

**Comment by BaseMax** [comment]
> Hey there,
> 
> This dwyl has been so interesting to go through. Can I join this organization? I can even blog out regarding technical stuffs.
> 
> Loved to be invited into. Cheers

Hey, Yeah
Welcome! :smiley: @iteles 
Regards, Max

**Comment by iteles** [comment]
@CoDeRgAnEsh I've sent you an invite! How did you find dwyl? 😊 

@BaseMax Love your enthusiasm 🎉 😄

**Comment by CoDeRgAnEsh** [comment]
I was looking up for content for my next tech blog and that's how i ended up here. 
Thanks for invitation @iteles @BaseMax  😃🤗

**Comment by poyea** [comment]
Hello! I'm stunned by all documentation of @dwyl. I believe the best way to understand a community is to learn, join and help build that community. Let's dwyl!

**Comment by BaseMax** [comment]
> Hello! I'm stunned by all documentation of @dwyl. I believe the best way to understand a community is to learn, join and help build that community. Let's dwyl!

Hi John @poyea ,

Welcome, I'm excited to watch your activity.

Cheers,
Max

**Comment by kittenking** [comment]
Hey there :wave:,

I like to contribute more to the @dwyl community with **awesome members** here!

**Can I join this organization?**

MUCH LOVE :blue_heart:

**Comment by sumanthratna** [comment]
I'm interested in joining. dwyl has helped me out plenty of times when picking up new languages, so I want to be able to contribute.

**Comment by BaseMax** [comment]
> I'm interested in joining. dwyl has helped me out plenty of times when picking up new languages, so I want to be able to contribute.

Hi Sumanth Ratna, @sumanthratna

Welcome. @iteles

Best,
Max

**Comment by iteles** [comment]
@sumanthratna So great to hear that! Welcome to dwyl 😊

**Comment by alan-oliv** [comment]
Hey people!

_"Change the world through technology"_ is literally my life mission!
The DWYL docs are stunning! I'd love to make part of this philosophy and contribute along with people who share the same beliefs. Can I join?

**Comment by iteles** [comment]
Happy to hear that @alan-oliv ! Welcome to dwyl ☺️

**Comment by TheAlemazing** [comment]
Hello folks!

Read all the docs within several days. I'd love to make part of this philosophy and contribute along with people who share the same beliefs. Can I join?

**Comment by AllenAJ** [comment]
Hey guys! 
I'd like to be a part of this open community. Can i please get an invitation?

**Comment by Neilblaze** [comment]
Hello Everyone :)
I would love to get my hands dirty on code with the community. Can I please have an invite?

**Comment by Neilblaze** [comment]
Hello Everyone :)
I would love to get my hands dirty by contributing to the community. Also looking forward to learn from seniors. Can I please have an invite?

**Comment by Neilblaze** [comment]
Hello Everyone :)
I would love to get my hands dirty by contributing to the community & also looking forward to learn new stuffs. Can I please have an invite?

**Comment by BaseMax** [comment]
> 
> 
> Hello Everyone :)
> I would love to get my hands dirty by contributing to the community & also looking forward to learn new stuffs. Can I please have an invite?

Hi @Neilblaze, Yes sure.
Welcome! 😃 @iteles
Regards, Max

**Comment by iteles** [comment]
@BaseMax, @Neilblaze accepted the invite 5 days ago ☺️  
![image](https://user-images.githubusercontent.com/4185328/68935872-3b042080-0791-11ea-931e-aea3f8fe85da.png)

**Comment by ikenjoku** [comment]
I absolutely love the tools🥳..I want to contribute 🙏🏽... I will like to join this awesome community.

**Comment by nelsonic** [comment]
@ikenjoku stoked you found us! welcome to the team! 🚀 
Is there anything particular you are keen on learning/contributing to? ❓

**Comment by ikenjoku** [comment]
Yay! @nelsonic   Going through Healthlocker got me thrilled at the profound impact we can have as technologists. I am excited at the thought of making our world a little easier for someone else. I’m 90% Javascript + (Python) and super excited to learn more and get busy with open-source projects making a difference.

**Comment by nelsonic** [comment]
@linuxenko that's awesome! [Healthlocker](https://github.com/healthlocker/healthlocker) is a great project with plenty of potential! 🥇 
`.js` and `.py` are _superb_ in-demand skills to have and focus on improving. 👍
Are you concentrating on front-end, back-end or "full stack"?

**Comment by ikenjoku** [comment]
It's "full stack" for me @nelsonic 😄

**Comment by maixiaojie** [comment]
hope to join @iteles

**Comment by BrendonCurmi** [comment]
Hey :) I love the project and explanations. They provide a great opportunity to learn; what a wonderful initiative! Would love to join the org and contribute. Could you pls send me an invite? Thanks a lot! @iteles

**Comment by yohix** [comment]
:heart: Hi! I would like to join and contribute! :heart:

**Comment by AngryYogurt** [comment]
I was looking up english words list and found [this](https://github.com/dwyl/english-words) . Now I would love to join this community and contribute. Thanks! :) @iteles

**Comment by Chaitanyassr** [comment]
Hi @iteles  i would love to contribute and join the organization.

**Comment by Ishaan28malik** [comment]
@iteles I would like to contribute to the projects and use my skills to enhance and add new features to the projects, especially the learn-phoenix-framework.
Let me know if I can join the organization.

**Comment by barhouum7** [comment]
I would love to join the dwyl community and contribute 😍❤

**Comment by alan-oliv** [comment]
> Happy to hear that @alan-oliv ! Welcome to dwyl ☺️

Hi @iteles! Thank you! Can I get and invitation to make part of the organization? I'd like to start helping out!

**Comment by tilakapash** [comment]
Hi, I'd like to join to try and give something back, as I have been "taking" (read: learning) so much from DWYL ...

**Comment by nelsonic** [comment]
@tilakapash stoked you discovered @dwyl and our learning resources. 🙌 
We strive to be a [Learning Organisation](https://en.wikipedia.org/wiki/Learning_organization) because we know from years of experience 
how _frustrating_ it is to work at orgs where learning is _not_ prioritised. 🤦 
If you are find anything you want to improve, please open issues+PRs 👍 
The most basic "giving back" we ask from people is to "star" the repos they find useful. ⭐ 
That way more people will discover them and contribute. 🚀

**Comment by jbampton** [comment]
Looks great !!  Starred, Forked and Watched :)   Would love an invite 👍

**Comment by sunilgknair051** [comment]
@iteles, would love an invite! Seems like a great place to learn and give back as well. :)

**Comment by spectralapps** [comment]
Heeey !
It would be great to join this community ! ⭐ 
Please send me an invite, Thanks. 🚀

**Comment by harshareddy794** [comment]
I love to contribute to open source projects so I want to join in the community

**Comment by bensums** [comment]
Pure maths, backend, data science here. The values are so in line with what I believe. Would love to get involved.

**Comment by dheerajkotwani** [comment]
Hello,
I would love to be part of this and contribute :)

**Comment by abhisheknaiidu** [comment]
Hello,
I would love to be part of this and contribute :)

**Comment by dheerajkotwani** [comment]
Hello,
I would love to join the dwyl community and contribute to it.

**Comment by naha7789** [comment]
Hello,
I would love to be part of this and contribute :)
@iteles

**Comment by varadp2000** [comment]
Hey,
I would love to be part of DWYL community and contribute.

**Comment by iteles** [comment]
@varadp2000 Great profile readme, very interesting read 😄  Welcome to dwyl!

**Comment by varadp2000** [comment]
@iteles Thank you so much. It will be fun working with you.😁

**Comment by Surajv311** [comment]
Hi, 
I would love to contribute and be a part of the community!

**Comment by bejoistic** [comment]
I would love to contribute :smiley_cat:

**Comment by shivaylamba** [comment]
Would love to get invited and contribute!

**Comment by Tanuj22** [comment]
Hey, 
I would love to contribute and be part of the dwyl community  :smile:

**Comment by midopooler** [comment]
Would love to get invited and contribute!

**Comment by Harshita-Kanal** [comment]
Hey!
I loved your ideas!
Would love to get invited and contribute!

**Comment by Jashpatel1** [comment]
Hey, I am an open source enthusiast. 
I would love to contribute and be a part of this community.

**Comment by Garvit-32** [comment]
Hi, 
I would like to contribute 😍

**Comment by loveneeshdhir** [comment]
Would love to get invited and contribute!

**Comment by Sumanth-Talluri** [comment]
Hello @iteles ,
I would love to contribute and be a part of the community!

**Comment by Brillianttyagi** [comment]
Hi,
I would like to contribute and be a part of this community 😍

**Comment by Potential17** [comment]
Hi,
I would love to contribute and be a part of the community!

**Comment by tomasmilkintas** [comment]
I'd also like to take part! Seems like a great opportunity to join something exciting!

**Comment by kpiyush04** [comment]
Would love to get invited and contribute!

**Comment by natnat201193** [comment]
Hello, I would Love to join if I can please! 👍

**Comment by goforitandy** [comment]
Me and my son please! 

Me, Andrew Carr:
https://github.com/goforitandy

And Nathan Catt
https://github.com/natnat201193

Thanks, 

Andy

**Comment by ArnavBalyan** [comment]
Hi, would love to be a part of this, can you please add me!

**Comment by Starkultra** [comment]
hey, I am prasath saw community projects its too good and motive of this community synchronize with my aim too. I Will be felt grateful if I selected to take part in dwyl community and collaborate with other dwyl developers in contributing to the open-source

**Comment by himanshu007-creator** [comment]
Hi, i loked the idea behind the community. please add me!

**Comment by Ayush7614** [comment]
Hi would love to be a part of this, can you please add me!

I am joining this community first of all i love to collobrate and contribute on github. I have also love met new people and help others i am doing web development android development and DSA I can take also part in various foss events and many winter of codes program i am top contributers in the kwoc and i am totally love with contribute on github so thats the reason i have to join this community and help peoples and looking forward to more contribute to the community

**Comment by DarkMarksDoe** [comment]
Hi, I'm Mark, System Engineer student, learning about Flutter, Machine Learning, Laravel and Linux.

And i would love to contribute in Flutter🦖

**Comment by nelsonic** [comment]
Hey @DarkMarksDoe 👋 
Stoked you found @dwyl and want to learn/contribute! 🎉 
@SimonLab is currently working on a Flutter Todo List tutorial: https://github.com/dwyl/flutter-todo-list-tutorial/pull/17 👨‍💻 
If you want to take a look at it with a fresh pair of eyes and give some feedback, it would be much appreciated. 🤞 
Thanks! 🙌

**Comment by gargk747** [comment]
Hello, my name is Keshav Garg. I am from India.
I Would like to join this organization.
I am an Android developer and wants to contribute in this area.
I love to contribute to open source and will love to contribute to this organization.
Please add me to your organization.

**Comment by mahendrarathore1742** [comment]
Hey  @iteles! Hey! I love it all! Can I join in? I would love to help to other.

**Comment by mahendrarathore1742** [comment]
@iteles if you could invite me too :)

**Comment by sergeyt** [comment]
Hi, I am universal Software Engineer from Russia. I am doing https://linguabook.github.io/ for everyone - it is aggregator of multiple data sources (usually online dictionaries) to help working with words. It seems I am already sharing your values 😄

**Comment by smm13344331** [comment]
Really interesting idea and  a lot of useful repositories. I'd love to contribute.

**Comment by Rey-commits** [comment]
I also love to join in this big community. I am excited to contribute.

**Comment by dboeke** [comment]
Love the mission and your opinionated approach to get people over the hurdles to contribute. Consider my interest peaked!  Am excited to learn PETE.

**Comment by Majalian** [comment]
would love to join as well!

**Comment by vikichand** [comment]
![image](https://user-images.githubusercontent.com/51986613/117971462-0a994480-b37e-11eb-9c09-7a300598c480.png)

I noticed Dwyl does not have Fiji listed in the community section, maybe we can change that ..

I would like to express my interest in meeting and learning more from the Dwyl community members and help contribute to your open-source projects. If you see me fit I would love to join 🙏

Thank you.

**Comment by nelsonic** [comment]
@vikichand Fiji! Wow! 🌴 ❤️  Welcome!

**Comment by pjdurden** [comment]
Hi, my name is Prajjwal. I am a third year computer science student from Delhi Technological University.
I love to contribute to open source and will love to contribute to this organization.
Please add me to your organization.

**Comment by alphaion** [comment]
Hey, this is Rishabh. I would love to be a part of this organization and I'll give my precious contribution in this org.

**Comment by thejaswin123** [comment]
Hi, I am Thejaswin S and would like to join this dwyl community and contribute to open source projects, and collaborate with other developers.

**Comment by sameer882000** [comment]
Hi, I am Sameer Sinha  and I would like to join this  community and contribute to open source projects, and collaborate with other developers.

**Comment by Ayushparikh-code** [comment]
I'd also like to take part! Seems like a great opportunity to join something exciting!

**Comment by LegendSumeet** [comment]
Hello. I saw the dayum interesting docs of this repo. Would love to contribute to the projects and flowering new ideas. Please send me invite to join this organisation

**Comment by RedJanvier** [comment]
Hello I'm Janvier and I wish to join and contribute to this community I believe in.

**Comment by smriad** [comment]
Hello, I am Riad,  like to join your community and glad to contribute

**Comment by Mobasherah12** [comment]
Hi there, I am Mobasherah. Interested to join this community and looking forward to contribute.

**Comment by BaseMax** [comment]
Welcome my friend Smriad, Mobasherah, Janvier, Anish, Sumeet, Ayush, Thejaswin, Rishabh, and Prajjwal. :+1: :heart:

**Comment by 0xMRTT** [comment]
I'd also like to take part! Seems like a great opportunity to join something amzing!

**Comment by amos-kibet** [comment]
Hello, Kibet here, an enthusiastic Elixir/JS developer from Kenya. I would love to be part of this amazing community and help spread the good work you're doing.

**Comment by vedantmgoyal2009** [comment]
I want to join the org.

**Comment by kiranrega** [comment]
I would also like to be part of this org and want to learn things.

**Comment by supercomet329** [comment]
Hi! I would like to join and contribute!

**Comment by charles0830** [comment]
Hi! I would like to join and contribute!

**Comment by rubiin** [comment]
I'd also like to Contribute to this Awesome Org and Learn Contribute Parallely.

**Comment by akash-tk** [comment]
Hi! I would like to join and contribute!

**Comment by dmitrii-esin** [comment]
Hi guys!

Trying to find opensource Elixir projects to contribute to, I found this community and repo. This initiative and project resonates with my core values.

What is the best way to join, is that community still active, and what should I do as my first step? 
The gitter community mentions frequently, but I was overwhelmed by articles and could not find the way to contribute.



Thanks in advance!

**Comment by nelsonic** [comment]
@dmitrii-esin follow-up question asked in: https://github.com/dwyl/start-here/issues/278#issuecomment-2566924734 ❓

**Comment by johnraivenolazo** [comment]
Hi! I would like to join and contribute!
