### ISSUE TITLE
Add link to Git and Github for Poets

### ISSUE THREAD

**Issue by YvesMuyaBenda** [dwyl/start-here#146]
The theme of this repository is the minimal amount of information to allow someone new in tech to make rapid progress in their first steps. To this end, I propose adding [Git and Github for Poets](https://www.youtube.com/playlist?list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV) as the top link in the Git and Github section. For me, it is the very best first step a beginner could take in learning Git and GIthub (uses simple examples someone not familiar with code will understand), and it works as a video tutorial to complement and clarify the other text-based resources. 

I intend to add the link myself as a nice small exercise in contributing to the READMES while respecting the contributing guidelines as per dwyl/contributing#95.

**Comment by nelsonic** [comment]
@YvesMuyaBenda good plan. 🎉
