### ISSUE TITLE
Review README

### ISSUE THREAD

**Issue by iteles** [dwyl/start-here#15]
A lot has happened since this readme was first authored! People finding dwyl will naturally gravitate to a repo called `start-here` so it should be a little more obvious what we do at dwyl in the first couple of sentences (and a clearer link to the manifesto).     
I still love most of this, I think it just needs to be updated.

**Comment by nelsonic** [comment]
Agree 100%! Please update as you see fit. (_or create a 2h task for someone you trust to write good copy..._ e.g: @msmichellegar ?)

**Comment by iteles** [comment]
PR #62
