### ISSUE TITLE
Add section on open source

### ISSUE THREAD

**Issue by YvesMuyaBenda** [dwyl/start-here#152]
User Story: As a beginner, I now know enough GIt and GitHub to create a pull request, but I need more context on open source, so I can feel more confident contributing to open source projects.

For me there is a hole between the end of the "Git + Github" section, and the end where we  ask/suggest the reader to go and contribute. I propose we add a section on open source in between "Git + Github" and "Design".

**Comment by newswim** [comment]
Here are a few resources that might be helpful:

- https://opensource.guide
- https://github.com/open-source

There's also a really great book which is free to read online:
- https://en.wikipedia.org/wiki/The_Cathedral_and_the_Bazaar

**Comment by olstenlarck** [comment]
Yup. OpenSource.guide is just perfect.

This also may help https://github.com/tunnckoCore/contributing. It's adapted from few places.

- https://medium.com/codezillas/a-bitter-guide-to-open-source-a8e3b6a3c1c4
- https://github.com/olstenlarck/resources
