### ISSUE TITLE
Add to touch typing section

### ISSUE THREAD

**Issue by YvesMuyaBenda** [dwyl/start-here#156]
User Story: As someone starting, I find it difficult to invest the effort to learn touch-typing, when I can easily copy and paste code or even [hunt and peck](https://www.urbandictionary.com/define.php?term=Hunt%20and%20Peck%20Typing). I need more information to convince me not to form bad habits, that will be difficult to correct later on.

User Story: As someone starting, I have learned to touch type all the letter, numbers. punctuation and other symbols on the keyboard, but I do not grasp the how and why I can carry on this basic skill into learning programming.

I propose we add two pieces of information to the end of the touch typing section:

+ Advice based on using example code that a learner will find in their resources for typing practice (i.e HTML quickly shows you how comfortable you are with right and left angle brackets, and each language has its own unique key combinations)
+ Articles that speak of the importance of typing  code by hand with learning how to code. Not only will this motivate the reader to learn to touch type properly in the first place, but it will allow them to easily observe how the skill is continually used in their adventure in learning to code!

**Comment by YvesMuyaBenda** [comment]
I myself very much enjoy touch typing!

**Comment by nelsonic** [comment]
@YvesMuyaBenda this is something I will be paying _particular_ attention to in the next few weeks... 😉

**Comment by YvesMuyaBenda** [comment]
@nelsonic Would you like me to divide this into two smaller issues? I just did a quick Google search on the semantics of the epic tag. I was going to do this in two rather short , easily read commits, since I did not want to needlessly ping folk for reviews.

**Comment by nelsonic** [comment]
@YvesMuyaBenda yeah, the _reason_ I consider this an `epic` is because I want to dedicate time to _build_ a touch-typing-tutorial 😮 😉 
But for the purpose of simply _updating_ the `start-here` readme, we can _remove_ the `epic` label. 👍

**Comment by YvesMuyaBenda** [comment]
@nelsonic Oh okay! Understood! That is some interesting timing. Are you talking about an app, or another README? I wonder if you would consider one of the next two commits I have in mind as epic, in the sense of being standalone? 🤔

**Comment by nelsonic** [comment]
@YvesMuyaBenda _both_ a README and an Open Source Elm App 
to teach people of all ages how to touch-type ... 
But I don't expect to _start_ on this "mini-project" for another month.
So in the _meantime_, please go ahead and update the readme.
I'd be keen to see your research on the subject. 🤔 
thanks! 👍

**Comment by YvesMuyaBenda** [comment]
@nelsonic Sorry, I deleted my post for its lack of succinctness and clarity. The original question: are you  building a README or an app?

Sure, the main though was to connect touch typing into learning how to program, which was going to be a precursor to a "How to Learn How to Learn" subsection.

**Comment by nelsonic** [comment]
"Coming soon": https://github.com/nelsonic/learn-touch-typing 😉

**Comment by YvesMuyaBenda** [comment]
@nelsonic The sticking point for applying it to programming is the symbols; for the alphabet and already knowing how to type them, the experience at [keybr](https://www.keybr.com) is pretty magical and addictive. I can often hit 90 wpm, but I struggle to hit 100 consistently, but there you go, typing out messages in Github becomes so nice and fluent, like I have grease in my knuckles!

Okay, I will add to the the section on touch typing tomorrow.

**Comment by YvesMuyaBenda** [comment]
Nah, might as well just write right now!
