### ISSUE TITLE
Add section on learning how to learn

### ISSUE THREAD

**Issue by YvesMuyaBenda** [dwyl/start-here#160]
User Story: As someone starting, I know that programming has a lot of learning curves, and my old habits that got me through school might not be appropriate any more: I would like some information that helps me think more consciously about how I am approaching learning to program, so I can learn more efficiently and gain good habits for the future.

Plan:

Add general subsection on learning how to learn.
Add subsection of talks that give different perspectives for learning how to learn applied to programming.
Add subsection of specific tricks and strategies, for example how to go about reading code.

The main question in my head is whether the section should come before or after the section on touch-typing? Any thoughts?

**Comment by YvesMuyaBenda** [comment]
If there are no counter-thoughts, the section will be added after the touch-typing section. My thought was that it would be useful if the person started working on a concrete skill, that of touch-typing, before being given thoughts about how to learn as applied to programming.

**Comment by nelsonic** [comment]
@YvesMuyaBenda sounds great! assign PR when ready. thanks! 🥇

**Comment by YvesMuyaBenda** [comment]
@nelsonic Will do!
