### ISSUE TITLE
Add Markdown Guide as a Resource for Learning Markdown

### ISSUE THREAD

**Issue by YvesMuyaBenda** [dwyl/start-here#167]
It is _here_:[Markdown Guide](https://www.markdownguide.org/book).

**Comment by nelsonic** [comment]
I just learned that it's _possible_ to add images with a specific width and `float: left` from reading _this_ PR: https://github.com/Microsoft/MS-DOS/commit/5286d044927f4f2f1e2dbd6b0bd326cdc6925a36#diff-04c6e90faac2675aa89e2176d2eec7d8R1 😮

**Comment by HeroicHitesh** [comment]
I would like to work on this issue.
And if I am correct we have to add

> [Markdown Guide](https://www.markdownguide.org/book).

to README of this repository.
My question is do we need to add link to file in README or upload the file in this repository.

**Comment by nelsonic** [comment]
A link to the resource is good. 💡

**Comment by HeroicHitesh** [comment]
Resolve issue #167 in commit 22e0595
