### ISSUE TITLE
dwyl stickers

### ISSUE THREAD

**Issue by iteles** [dwyl/start-here#17]
These need to happen. Because they're awesome. And because our friends love stickers and will absolutely support us if we add a little awesomeness to their laptops.

Tasks:
- [x] Determine design for stickers
- [x] Define budget
- [x] Research and get quotes 
- [x] Order

**Comment by iteles** [comment]
Proposed MVP designs (just so we have something for now, design to be severely improved upon
![dwyl-sticker -all-white](https://cloud.githubusercontent.com/assets/4185328/8003648/498691e0-0b71-11e5-9393-9928760afaab.PNG)
![dwyl-sticker -all-white-smallio](https://cloud.githubusercontent.com/assets/4185328/8003652/4d4b2890-0b71-11e5-9b1c-860ebe48bf30.PNG)
![dwyl-sticker -all-white-logo-in-text](https://cloud.githubusercontent.com/assets/4185328/8003654/4f164f2e-0b71-11e5-8bd9-c7f6096e4da6.PNG)
![dwyl-sticker -dark-heart-smallio](https://cloud.githubusercontent.com/assets/4185328/8003646/486fcc04-0b71-11e5-8697-fce987112d38.PNG)
![dwyl-sticker -dark-heart](https://cloud.githubusercontent.com/assets/4185328/8003649/4b3aeee6-0b71-11e5-9006-e55c47d34aa5.PNG)

**Comment by nelsonic** [comment]
as "MVP" (and then #**backup** when our "*real*" stickers run out!) stickers these will be perfect!

**Comment by iteles** [comment]
Went with the first design for simplicity although I think it has no interest and really needs *something*. 
Ordered 300 x 50x50mm  and 19 larger ones from www.fastprint.co.uk/adhesive-stickers-labels/gloss-stickers.html

**Comment by nelsonic** [comment]
#***exciting***!! :+1:

**Comment by iteles** [comment]
Officially documented in www.github.com/dwyl/print-me

**Comment by nelsonic** [comment]
#Winning!

**Comment by iteles** [comment]
@nelsonic well, it will be once you merge https://github.com/dwyl/print-me/pull/10 :wink:

**Comment by iancrowther** [comment]
not a hex in sight :-(

**Comment by iteles** [comment]
@iancrowther I know! That is **absolutely** the plan for our next batch, hexes are a bit harder to cut out with our [DIY corner-punch approach approach](https://cloud.githubusercontent.com/assets/4185328/8397977/b1b08d76-1dd6-11e5-8433-ea88775151a4.jpg) this time around.     
We may even create special dev stickers for our contributors (naturally hexes) and then app icon looking stickers as well... I'm interested in seeing who will actually want these stickers and then going from there.

**Comment by nelsonic** [comment]
Yeah, @iancrowther we will be producing the "real" stickers (including ***hex*** ones)
when we launch the app.

these are only the "_alpha_" stickers ... :wink:
