### ISSUE TITLE
Suggest Engaging in hacktoberfest

### ISSUE THREAD

**Issue by pscott-au** [dwyl/start-here#171]
Call to contributors to participate in 
https://hacktoberfest.digitalocean.com/#projects

> To get a shirt, you must make five pull requests (PRs) between October 1–31 in any timezone. PRs can be to any public repo on GitHub, not just the ones highlighted. The PR must contain commits you made yourself (not to your own repo). PRs reported by maintainers as spam or that are automated will be marked as invalid and won't count towards the shirt. This year, the first 50,000 of you can earn a T-shirt (compared with 30,000 in 2017).

Consider tagging DWYL Repo Issues with the 'Hacktoberfest' tag to open up to an eager user base.

**Comment by iteles** [comment]
@pscott-au Thank you for this suggestion! We added the Hacktoberfest label to a few issues across our projects and although they didn't get a lot of traction, we came to it pretty late in the game!

This is a great suggestion though and we'll definitely look to do it next year.

Shall we close this issue for now and reopen in the summer when it's relevant?
