### ISSUE TITLE
GitHub Command Line (SSH) Access (Setup Instructions)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/start-here#18]
If you have not already setup your computer to access github using ssh, the follow these instructions: https://help.github.com/articles/generating-ssh-keys/

**Comment by nelsonic** [comment]
should we add this to the **New Developer Checklist** ?
CC: @anniva ...

**Comment by iteles** [comment]
This has been captured in https://github.com/dwyl/dev-setup#basic-git-setup and https://github.com/dwyl/start-here#setup-for-coders
