### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by iteles** [dwyl/start-here#20]
Need to create a general code of conduct for dwyl, linked to https://github.com/dwyl/summer-2015/issues/8
_(Create in separate repo for general use)_

**Comment by nelsonic** [comment]
Yes, please create a repo for this. *thanks*! :+1:

**Comment by iteles** [comment]
Here's our start: https://github.com/dwyl/code-of-conduct
@nelsonic Reckon we could close this issue for now and add refinement issues to the code of conduct repo :blush:

**Comment by nelsonic** [comment]
We can close it when people read it...

**Comment by nelsonic** [comment]
We need  a way of people confirming they have read something ... closing.

**Comment by iteles** [comment]
@nelsonic Agreed! For now it's in the freelance agreement and I'll get verbal confirmation.
