### ISSUE TITLE
Request for Joining 

### ISSUE THREAD

**Issue by geekyvyas** [dwyl/start-here#207]
Hey My name is Yajush.
I am from India.
I Would like to join this organisation.
I love to contribute in open source and will love to contribute in this organisation.
Please add me in your organisation.

**Comment by nelsonic** [comment]
Hi @geekyvyas, 👋 
invite sent. 📥 
How did you find out about @dwyl ? 😊

**Comment by geekyvyas** [comment]
I love to contribute for the community, so I asked my friend for an organisation which is helpful to others, so he named yours and in this way I came to know about your organisation. I am very much looking forward to contribute with you on some projects.
Thank you

**Comment by nelsonic** [comment]
@geekyvyas thanks for informing. 🙌
