### ISSUE TITLE
Request for joining the Organization

### ISSUE THREAD

**Issue by riturajjain2000** [dwyl/start-here#209]
Hello, my name is Rituraj. I am from India.
I Would like to join this organization.
I love to contribute to open source and will love to contribute to this organization.
Please add me to your organization.

**Comment by nelsonic** [comment]
Hi @riturajjain2000, 👋 
you've been invited. 📥 
How did you discover @dwyl? 💭 

Relates to #143 🔗

**Comment by riturajjain2000** [comment]
I was searching for organizations that I can be a part of and make contributions to when I came across your organization, and it looked like a great place to be a part of !!

**Comment by nelsonic** [comment]
@riturajjain2000 thanks for letting us know. 👍

**Comment by nelsonic** [comment]
Closing as invite sent. ✅
