### ISSUE TITLE
Joining issue 

### ISSUE THREAD

**Issue by jishanshaikh4** [dwyl/start-here#218]
Simple, starring the repo should not be a great idea to expand the organization. Maybe a simple set of questions as a template (e.g. I love _______ languages, I like __________ doing things, etc.) on the issue would be a great addition to starring the repo!

That would be convenient as well.

**Comment by jishanshaikh4** [comment]
Maybe add me as well :laughing:

**Comment by nelsonic** [comment]
@jishanshaikh4 thanks for opening this issue. 👍 
We removed our script that automatically added people who starred the repo a while back.
But we've been thinking of asking people a couple of simple questions when they discover @dwyl 💭 
Hence: https://github.com/dwyl/start-here/blob/master/questions.md (which is way too many questions!)

**Comment by nelsonic** [comment]
P.S. sent you an invite.

**Comment by jishanshaikh4** [comment]
Yeah, too many questions, fine. :sweat_smile: 

Thanks btw @nelsonic, really appreciated.
