### ISSUE TITLE
Request to join the dwyl organization

### ISSUE THREAD

**Issue by iamrubayet** [dwyl/start-here#223]
thank you

**Comment by nelsonic** [comment]
Hi @iamrubayet 👋 
How did you learn about @dwyl? 💭

**Comment by Estevamsl** [comment]
Because I want to stay on top of everything that goes on in this organization and of course, as a good dev, you have to know about the challenges of this incredible world of programming

**Comment by nelsonic** [comment]
Thanks @Estevamsl. 👍 
Invites sent. ✉️ 
Closing. ✅
