### ISSUE TITLE
Request to join the organization

### ISSUE THREAD

**Issue by m0lese** [dwyl/start-here#225]
I would like to join the organization to learn and contribute :D

**Comment by nelsonic** [comment]
Hi @m0lese, 👋 
Welcome to @dwyl 🎉 
Quick question: how did you discover the org? 💭 
Invite to join sent to your email/GH notifications. ✉️ 

Love the variety on your GitHub. Great range of contributions/skills. 🥇 
![image](https://user-images.githubusercontent.com/194400/135611128-fd03920b-0f8c-4539-b0f2-0d21205e15dd.png)

That GH Contrib graph snake game is sick!  https://github.com/Platane/snk 🐍 
![](https://github.com/Platane/snk/raw/output/github-contribution-grid-snake.svg)

Hope you have a great day and weekend! ☀️

**Comment by m0lese** [comment]
Q: how did you discover the org?
A: I found it on [jbampton](https://github.com/jbampton)'s profile.

Thank you very much :D . Feels awesome to be a part of dwyl.
You too have a wonderful day and weekend.
