### ISSUE TITLE
Request to join dwyl

### ISSUE THREAD

**Issue by Arhell** [dwyl/start-here#226]
Hi, I would like to work on the organization's frontend resources (bug fixes, UI improvements, accessibility, and more)
for example https://github.com/dwyl/dwyl-site

**Comment by nelsonic** [comment]
Hi @Arhell, 👋 
Welcome to @dwyl! 
Very happy to have you on-board.
How did you discover us?

**Comment by Arhell** [comment]
> Hi @Arhell, 👋 Welcome to @dwyl! Very happy to have you on-board. How did you discover us?

Hello, I saw the icon in the organization table. But I don’t remember which user, unfortunately.

I went to this icon, wrote here.
Thank you for the attention.
