### ISSUE TITLE
Request for joining the Organization

### ISSUE THREAD

**Issue by Hardly-Human** [dwyl/start-here#230]
Hello, my name is Rehan and I am from India.
I Would like to join this organization.
I love to contribute to open source.

**Comment by nelsonic** [comment]
Hi Rehan, welcome to @dwyl. 👋

**Comment by Estevamsl** [comment]
Because I want to stay on top of everything that goes on in this organization and of course, as a good dev, you have to know about the challenges of this incredible world of programming

**Comment by nelsonic** [comment]
Thanks for the reminder to close this. ✅
