### ISSUE TITLE
Please invite me to your organization!

### ISSUE THREAD

**Issue by thuongtruong1009** [dwyl/start-here#239]
Hi there!
My name is Tran Nguyen Thuong Truong - @thuongtruong1009
Currently, I learning front-end.
I want to learn more and more about open-source code.
Hope to cooperate with you in the future.
Thank you!

**Comment by nelsonic** [comment]
Hi @thuongtruong1009 glad you found dwyl. Check your inbox for invite. 🙌

**Comment by thuongtruong1009** [comment]
> Hi @thuongtruong1009 glad you found dwyl. Check your inbox for invite. 🙌

Thank you very much, bro!
You're handsome 🥰
