### ISSUE TITLE
new intro image?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/start-here#24]
I quite like the sho shin symbol: 
![sho+shin](http://i.imgur.com/p538Ld2.jpg)

But I prefer:
![dwyl-logo-wide](https://cloud.githubusercontent.com/assets/194400/8141150/f4b4c854-115a-11e5-8c13-dc96a5f1e928.png)

What do ***you*** think?

**Comment by iteles** [comment]
For now I agree it makes sense to go with the dwyl logo for what's technically the first repo anyone sees :blush:
Already added to PR #23
