### ISSUE TITLE
I'm interested in joining dwyl and would love to contribute in your work.

### ISSUE THREAD

**Issue by jyotsnad246** [dwyl/start-here#249]
I would love to contribute to dwyl.

**Comment by nelsonic** [comment]
Hi @jyotsnad246 welcome to @dwyl 👋 
How did you discover us? 🔍

**Comment by jyotsnad246** [comment]
I like to contribute to open source projects with other people and I came across @dwyl through a friend's profile. So, I want to join this organization to learn and contribute to projects.

**Comment by nelsonic** [comment]
@jyotsnad246 good to know. Thanks. 👌 
If you have _any_ feedback please share. 🙏 
Hope you have a great day. ☀️
