### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by Sinrez** [dwyl/start-here#268]
Hello.
I am interested in new technologies and language.
I am currently learning Python.
This project is interesting for my self-education

Thank you for the opportunity

Regards, Alex

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/230488321-0d9d6457-e4ee-4d95-adab-42735cad688c.png)

**Comment by Sinrez** [comment]
Thank you! ok)

**Comment by Deykun** [comment]
@nelsonic
Hey, could you also invite me? I would like to review some PRs in `english-words` and merge them. Thanks!
