### ISSUE TITLE
Suggested Touch Typing Tutorials?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/start-here#27]
> add these links and text to the touch-typing section of the readme:

+ BBC: http://www.bbc.co.uk/guides/z3c6tfr#zg8nsbk
+ Typing Club: http://www.typingclub.com/typing-qwerty-en.html
If you know/find a better (_online_) touch typing tutorial, please share it with us: 
https://github.com/dwyl/start-here/issues (_thanks_!)

**Comment by Danwhy** [comment]
I found this one a few days ago that looks quite good: http://www.keybr.com/

**Comment by nelsonic** [comment]
@Danwhy that's a *fantastic* find! Thanks! :+1:

**Comment by nelsonic** [comment]
@Danwhy would you mind sending us a Pull Request adding these links (yours first as its _easily the best resource_!) to the Touch Typing section of the Readme? Also, if you spot any other areas for improvement, please go for it! thanks! hope you have a good evening. :+1:

**Comment by nelsonic** [comment]
@Danwhy kindly PR'd his *touch-typing tutorial* suggestions into the readme. this can be closed.
