### ISSUE TITLE
Encourage all Developers to Enable Two-Factor Authentication

### ISSUE THREAD

**Issue by nelsonic** [dwyl/start-here#28]
Two-Factor Auth makes your GitHub account Secure.

See:
- https://www.authy.com/
- https://help.github.com/articles/about-two-factor-authentication/

**Comment by nelsonic** [comment]
@iteles please enable 2-Factor Auth for your GitHub account.
(yes, this will mean you need to have your phone on you when ever you login to GitHub ... but ...)
It will mean that **dwyl** has a much lower chance of having projects deleted by a rogue or account hacker...

**Comment by iteles** [comment]
:+1: Mine's been enabled for ages, totally agree!
<img width="376" alt="screen shot 2015-07-18 at 15 37 00" src="https://cloud.githubusercontent.com/assets/4185328/8761972/077584a0-2d63-11e5-87d2-4bbe73e7c284.png">

**Comment by msmichellegar** [comment]
Enabled!

**Comment by iteles** [comment]
@dwyl/doers On it?

**Comment by tsop14** [comment]
Done!

**Comment by iteles** [comment]
@tsop14 :+1: :heart:
