### ISSUE TITLE
Definition of Done?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/start-here#33]
@iteles while reviewing the **freelance agreement**: https://github.com/dwyl/summer-2015/blob/9ee717657115de822916838833cab8d2ef9be9b7/freelance-agreement.md I noted an omission...
we need to craft our _**Definition of Done**_ for **dwyl**. 
There can be _no ambiguity or imprecision_ in the language. 
Please let me know when you have time this evening.

For others following along who are not familiar with this expression, please read:
- http://guide.agilealliance.org/guide/definition-of-done.html
- https://www.scrumalliance.org/community/articles/2008/september/what-is-definition-of-done-(dod)

**Comment by nelsonic** [comment]
Part of completing the task is: 
+ summarising the _implementation detail_ for the solution you wrote
+ logging the _actual_ time the task took to complete

**Comment by nelsonic** [comment]
@iteles maybe its time to finish this...? :wink:

**Comment by iteles** [comment]
@nelsonic Want to pair on something tomorrow and create an **amazing example** that we can add to the definition of done?

**Comment by iteles** [comment]
Repo created here: https://github.com/dwyl/definition-of-done

Must add links in start-here before this issue can be closed. All future issues on this topic can be moved to new repo.

**Comment by nelsonic** [comment]
Thanks @iteles  :+1:

**Comment by iteles** [comment]
:candy:  :wink:

**Comment by iteles** [comment]
Closing as per https://github.com/dwyl/contributing/issues/109
