### ISSUE TITLE
Typo in JSON boilerplate for books to read?

### ISSUE THREAD

**Issue by jackpandas** [dwyl/start-here#35]
https://github.com/dwyl/start-here/blob/master/books-to-read.md

"SuggestdBy" as a key in the JSON - is this intentional? If not, maybe catch it now before it propagates?

**Comment by nelsonic** [comment]
Well spotted. Please PR find-and-replace to fix. Most people still haven't submitted. Thanks!

**Comment by jackpandas** [comment]
Would it be okay to merge my PR first so that I don't have to do it twice? ;)

**Comment by nelsonic** [comment]
Hi, yes, sorry, assigned to @iteles But super busy packing. Merged. Please proceed. Thanks!
