### ISSUE TITLE
Fan Fact: Emojis in Commit Messages is a Thing!

### ISSUE THREAD

**Issue by nelsonic** [dwyl/start-here#49]
Exploring Expressions of Emotions in GitHub Commit Messages 
http://geeksta.net/geeklog/exploring-expressions-emotions-github-commit-messages/

cc: @iteles @tsop14  :wink:

**Comment by NataliaLKB** [comment]
Haha enjoyed many of the example commit messages:

"This is getting very interesting right now. I'm excited. (JavaScript)"
"we we we so excited (JavaScript)"
"I'm a moron. Really glad I have the test server. (JavaScript)"
"I've added a feature :) #proud (C#)"
"The PHP commit. Yes, THE one. (Python)"

**Comment by nelsonic** [comment]
Yeah, lol! :laughing: 
Expressiveness in commit messages is #winning

**Comment by iteles** [comment]
:laughing: What a great post!!

I'm a fan of the matter-of-factly: _"Got mad, removed everything from top-level file."_
