### ISSUE TITLE
'Set up your development environment' guide for new developers

### ISSUE THREAD

**Issue by iteles** [dwyl/start-here#53]
As discussed in https://github.com/dwyl/summer-2015/issues/22#issuecomment-129167928

<img width="783" alt="set-up-your-developer-environment" src="https://cloud.githubusercontent.com/assets/4185328/9229259/2118feb8-4114-11e5-9b0e-4c284bc7ef15.png">

To include:
+ Text editor
  + Installing linter
  + Setting up tabs to spaces (2)
  + Column editing 
  + 80 character line length guide
  + Syntax guide
+ iTerm (and summary of why you would use more than one terminal window at once)

**Comment by tsop14** [comment]
https://help.github.com/enterprise/11.10.340/admin/articles/ssl-configuration/

**Comment by tsop14** [comment]
Here is a photo to use to show people where to change url from HTTPS to SSH

![screen shot 2015-08-12 at 20 04 14](https://cloud.githubusercontent.com/assets/8484757/9233887/8ff29ec0-412d-11e5-84ca-e0b92e7cef6d.png)

**Comment by iteles** [comment]
<img width="511" alt="80-character-line-guide-setup" src="https://cloud.githubusercontent.com/assets/4185328/9826015/45796748-58cf-11e5-8a5d-db7350a8eb82.png">

**Comment by iteles** [comment]
<img width="1221" alt="iterm-screenshot src="https://cloud.githubusercontent.com/assets/4185328/9831158/56d8cb90-5943-11e5-99ec-9fb1a5907f8a.png">
