### ISSUE TITLE
Learn Git / GitHub using the official guide

### ISSUE THREAD

**Issue by nelsonic** [dwyl/start-here#58]
https://guides.github.com/activities/hello-world/

**Comment by fmoliveira** [comment]
I know the thread is about using the official guide, but there's a good companion I couldn't resist mentioning.

The [git-it workshop](https://github.com/jlord/git-it) by @jlord is also a very good source of learning. It should be used with its own HTML help pages, which will guide you through setting up Git, creating your first repo, forking somebody's else repo, and creating a pull request. It'll also check if you've done your job right and point you about your mistakes.

By the end of the workshop you'll have some green squares in your profile and your name in the [patchwork website](http://jlord.us/patchwork). :smiley:

**Comment by iteles** [comment]
Thanks @fmoliveira, good to know about it!

**Comment by nelsonic** [comment]
Good addition. :+1:

**Comment by jlord** [comment]
Awesome! Thank @fmoliveira! We use both the Hello World Guide (mentioned at the top of the issue) and Git-it at the [GitHub Patchwork](https://patchwork.github.io) events. The former is a good one for people who aren't ready for the command-line as it's all web-based GitHub functionality. 

Just a note, I've been making a new version of [Git-it](http://github.com/jlord/git-it-electron) with [atom/electron](http://github.com/atom/electron) and have a [beta version](http://github.com/jlord/git-it-electron/releases) ready. This makes it a desktop app that runs on Linux, Windows and Mac :sparkles:

**Comment by nelsonic** [comment]
@jlord your new **Git-it** is *sweet*! :lollipop: 
We'll recommend it to our new joiners! :+1:

**Comment by iteles** [comment]
Thanks @jlord, it'll be a great addition for new coders!

**Comment by fmoliveira** [comment]
Thanks for the note @jlord ! The new Git-it looks very awesome! The idea of desktop workshops is brilliant! :wink:

**Comment by jlord** [comment]
@fmoliveira Thanks! Still have some polishing to do on it but then I want to make a re-useable workshop template.

**Comment by fmoliveira** [comment]
Good job @jlord ! You're awesome!
