### ISSUE TITLE
Atom Editor Plugin for tracking markdown in preview pane

### ISSUE THREAD

**Issue by nelsonic** [dwyl/start-here#59]
@iteles can you please remind us which atom plugin you are using to track the section you are editing in Markdown doc? thanks!

**Comment by nelsonic** [comment]
Is this it: https://atom.io/packages/markdown-scroll-sync ?

**Comment by iteles** [comment]
That's the one but don't get it yet! My markdown preview isn't working properly so I'm investigating the issue!

**Comment by nelsonic** [comment]
Ah, I installed but its intermittent... :disappointed:

**Comment by iteles** [comment]
Mine works in terms of scrolling, but the markdown preview itself has stopped recognising titles:

<img width="446" alt="screen shot 2015-08-31 at 12 25 24" src="https://cloud.githubusercontent.com/assets/4185328/9577728/c1540410-4fdb-11e5-9b3e-0287a9b6af17.png">

**Comment by iteles** [comment]
Turns out that atom was just being pissy about not having a space between the hash and the title itself (all of a sudden).

The markdown scroll isn't perfect, but it's a start. It's definitely the best one I've found so far.
