### ISSUE TITLE
Learn CSS in 1hour video

### ISSUE THREAD

**Issue by nelsonic** [dwyl/start-here#69]
@iteles again, as noted by @blossomica the Learn CSS Video
link we had shared is broken! (because "MammothInteractive" wants people to *pay* for their content ...)

Please help source an alternative. thanks!

**Comment by iteles** [comment]
On it.

**Comment by iteles** [comment]
That same tutorial is still available: https://www.youtube.com/watch?v=bRp00jkkGeg
But it's not actually that great. 

http://learn.shayhowe.com/html-css/getting-to-know-css/ and http://learnlayout.com/ aren't videos, but the information itself is much better.

**Comment by nelsonic** [comment]
@iteles agreed. but we *need* videos! :stuck_out_tongue:

**Comment by iteles** [comment]
https://www.youtube.com/watch?v=mzlqjRYszoI&list=PLEAFE1C118B3ED6AE Not bad but _so long_.

**Comment by nelsonic** [comment]
Quintin's videos are *good* but we can do a *lot* better. :wink:

**Comment by enociz** [comment]
I fixed a bug on [this](http://marksheet.io/) OS project before - do you think the content here is good? If so, maybe use it as a base for making our own videos.
