### ISSUE TITLE
JavaScript 1 hour intro tutorial

### ISSUE THREAD

**Issue by nelsonic** [dwyl/start-here#70]
again, as noted by @blossomica the Learn JavaScript video has been taken down... :sob: 
![Uploading broken-youtube-links.png…]()

I'm beginning to think we need to re-prioritise #ProjectVideo ... https://github.com/dwyl/video/issues

**Comment by iteles** [comment]
This series is pretty good: https://www.youtube.com/watch?v=fGdd9qNwQdQ&list=PLoYCgNOIyGACTDHuZtn0qoBdpzV9c327V

Still not perfect, we need to develop our own one!
