### ISSUE TITLE
what was I supposed to be doing?

### ISSUE THREAD

**Issue by rjmk** [dwyl/start-here#71]
Hey! I think I good pinged in some notifications recently and totally want to get round to them but I'm not very good at finding my way through my notification history. Any suggestions on working out what I was supposed to be doing?

**Comment by iteles** [comment]
@rjmk Hey! :blush: 

If you reckon they were _dwyl_ issues, then I reckon your easiest search query in GH is: `user:dwyl is:open rjmk` (or leave out the is:open in case you want to see some that might have been closed already).

Maybe more generally also try `assignee:rjmk is:open` just in case :wink:

**Comment by rjmk** [comment]
Amazing, thank you!
