### ISSUE TITLE
Coursera internet history course.

### ISSUE THREAD

**Issue by howardroark** [dwyl/start-here#74]
I highly recommend this course... https://www.coursera.org/learn/internet-history

It does a wonderful job of giving perspective for how the internet came to be.  It is full of first hand accounts from the people involved in creating all the bits.  I find a lot of people are pretty fuzzy in terms of how they see all of this.

One thing it does well is reassure people that things are not being "reinvented" every day.  There is a history of foundational elements that have been unchanging since to 70s.  A lot of the way technology is represented today can make people feel overwhelmed and that they could never possibly keep up.  I blame it on hype and marketing.

Plus it is free :)

**Comment by nelsonic** [comment]
@howardroark this is a *great* find! :+1: 
thanks for sharing. would you mind PullRequesting it into the body of the README?

**Comment by sofer** [comment]
@nelsonic this was on the FAC course prereqs but we culled it, because we have so many and some people thought it unnecessary. Personally, I was a bit sad. I might sneak it back on again.

**Comment by howardroark** [comment]
It is quick and easy too.  Great course for just loading up on the mobile app and watching during your commute.

**Comment by nelsonic** [comment]
@sofer *who* voted to remove it from [FAC](http://www.foundersandcoders.com/about/) pre-reqs? 

Sure, there are *many* things to tick off, but I'd recommend people *understand* the internet *every time* over more code wars... e.g. knowing about TCP is super useful.

The thing I *most* like about Coursera courses is their LinkedIn integration. 
See: @nofootnotes LinkedIn as a great example which lists the courses taken: https://www.linkedin.com/in/claireimitchell (*scroll down to certifications*) 
... CVs are *ancient history*. LinkedIn *won*. and if people *realise* that they will get "*credit*" for their learning in *addition* to the *intrinsic* reward of the *knowledge acquired*. 
Both from a team-member selection and potential employer perspective seeing that a person has *proactively* done Coursera Courses is a *massive* attraction that we should *emphasise*/*encourage*.
