### ISSUE TITLE
Manifesto Tidy Up

### ISSUE THREAD

**Issue by nelsonic** [dwyl/start-here#80]
should we tidy this...?
https://github.com/dwyl/start-here/blob/f57379b7a5101ffb67023ad3a8540ea04a0396f9/manifesto.md

**Comment by iteles** [comment]
Feel free to PR at will!

**Comment by enociz** [comment]
## 🤔 Why/What?

As Ernest Hemingway said, "The first draft of anything is shit" (💩). I wouldn't go to that extent with this manifesto but it could use some work.

## 💰 So, what do we need?

The current one is short (Hemingway likes 🙂) but it doesn't cover too much (Hemingway dislikes 🙁). Thus, we need a comprehensive and Hemingway-approvable manifesto to help people "do what [they] love".

## 💡 Suggestion

I suggest we brainstorm exactly what's needed in a manifesto and write that up as a dot-point draft on the file before going any further into expanding on those points.

**Comment by iteles** [comment]
@enociz What would you like to see in a manifesto?

**Comment by iteles** [comment]
The main tidy-up point required here is to make this less app-focused and more organisation-focused (i.e. points such as 'reward loyalty, not sign ups' will be moved to a more Product-specific manifesto rather than the main one).

**Comment by markwilliamfirth** [comment]
Linked to https://github.com/dwyl/hq/issues/328

**Comment by nelsonic** [comment]
This was updated a **`while`** ago: https://github.com/dwyl/start-here/blob/63468a6bc020f88c762465823da7419478f29687/manifesto.md

Closing. ✅
