### ISSUE TITLE
update list of people?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/start-here#9]
https://github.com/dwyl/start-here/tree/6cb32bda0f987dbbdc0889b4a64c74bfd91ac91a#who

**Comment by nelsonic** [comment]
This list should just be a link to: https://github.com/orgs/dwyl/people 
@iteles thoughts?

**Comment by iteles** [comment]
Yes, but I'd quite like to have a specific link for _contributors_ as well the _collaborators_ actually inside the organisation.

I've been googling for how to get this list for an **organisation** rather than for a repo but no joy yet.

**Comment by nelsonic** [comment]
Agree. we need a link to each person. I'd say it should be on our "About" page of the website tho... which will have a corresponding **.md** file in https://github.com/dwyl/dwyl.github.io

**Comment by nelsonic** [comment]
![dwyl-people](https://cloud.githubusercontent.com/assets/194400/9907174/b4a9202c-5c85-11e5-95b6-e070ce484920.jpg)

**Comment by iteles** [comment]
Linked to #139 and closed with https://github.com/dwyl/start-here/pull/140
